// <auto-generated />
using System;
using CreativeLongform.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CreativeLongform.Infrastructure.Migrations
{
    [DbContext(typeof(CreativeLongformDbContext))]
    [Migration("20260409204239_WorldElementLinkRelationDetail")]
    partial class WorldElementLinkRelationDetail
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CreativeLongform.Domain.Entities.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentStyleNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MeasurementPreset")
                        .HasColumnType("integer");

                    b.Property<string>("MeasurementSystemJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("StoryToneAndStyle")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Synopsis")
                        .HasMaxLength(16000)
                        .HasColumnType("character varying(16000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("Title");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("CreativeLongform.Domain.Entities.Chapter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsComplete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("BookId", "Order")
                        .IsUnique();

                    b.ToTable("Chapters");
                });

            modelBuilder.Entity("CreativeLongform.Domain.Entities.ComplianceEvaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GenerationRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("Passed")
                        .HasColumnType("boolean");

                    b.Property<string>("VerdictJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("GenerationRunId");

                    b.ToTable("ComplianceEvaluations");
                });

            modelBuilder.Entity("CreativeLongform.Domain.Entities.GenerationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<string>("FinalDraftText")
                        .HasColumnType("text");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("MaxRepairIterations")
                        .HasColumnType("integer");

                    b.Property<int?>("MinWordsOverride")
                        .HasColumnType("integer");

                    b.Property<Guid>("SceneId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<bool>("StopAfterDraft")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("SceneId", "IdempotencyKey");

                    b.ToTable("GenerationRuns");
                });

            modelBuilder.Entity("CreativeLongform.Domain.Entities.LlmCall", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BookId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GenerationRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("RequestJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ResponseText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Step")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("GenerationRunId");

                    b.ToTable("LlmCalls", t =>
                        {
                            t.HasCheckConstraint("CK_LlmCall_GenerationOrBook", "\"GenerationRunId\" IS NOT NULL OR \"BookId\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("CreativeLongform.Domain.Entities.Scene", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApprovedStateTableJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("BeginningStateJson")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("ChapterId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExpectedEndStateNotes")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasMaxLength(16000)
                        .HasColumnType("character varying(16000)");

                    b.Property<string>("LatestDraftText")
                        .HasColumnType("text");

                    b.Property<string>("NarrativePerspective")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("NarrativeTense")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Synopsis")
                        .IsRequired()
                        .HasMaxLength(16000)
                        .HasColumnType("character varying(16000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId", "Order")
                        .IsUnique();

                    b.ToTable("Scenes");
                });

            modelBuilder.Entity("CreativeLongform.Domain.Entities.SceneWorldElement", b =>
                {
                    b.Property<Guid>("SceneId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorldElementId")
                        .HasColumnType("uuid");

                    b.HasKey("SceneId", "WorldElementId");

                    b.HasIndex("WorldElementId");

                    b.ToTable("SceneWorldElements");
                });

            modelBuilder.Entity("CreativeLongform.Domain.Entities.StateSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GenerationRunId")
                        .HasColumnType("uuid");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer");

                    b.Property<string>("StateJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Step")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GenerationRunId");

                    b.ToTable("StateSnapshots");
                });

            modelBuilder.Entity("CreativeLongform.Domain.Entities.TimelineEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrencyPairAuthority")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("CurrencyPairBase")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("CurrencyPairExchangeNote")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("CurrencyPairQuote")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SceneId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("SortKey")
                        .HasColumnType("numeric");

                    b.Property<string>("Summary")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid?>("WorldElementId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SceneId")
                        .IsUnique();

                    b.HasIndex("WorldElementId");

                    b.HasIndex("BookId", "SortKey");

                    b.ToTable("TimelineEntries");
                });

            modelBuilder.Entity("CreativeLongform.Domain.Entities.WorldElement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("Provenance")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BookId", "Slug")
                        .IsUnique()
                        .HasFilter("\"Slug\" IS NOT NULL");

                    b.ToTable("WorldElements");
                });

            modelBuilder.Entity("CreativeLongform.Domain.Entities.WorldElementLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FromWorldElementId")
                        .HasColumnType("uuid");

                    b.Property<string>("RelationDetail")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("RelationLabel")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("ToWorldElementId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ToWorldElementId");

                    b.HasIndex("FromWorldElementId", "ToWorldElementId", "RelationLabel")
                        .IsUnique();

                    b.ToTable("WorldElementLinks");
                });

            modelBuilder.Entity("CreativeLongform.Domain.Entities.Chapter", b =>
                {
                    b.HasOne("CreativeLongform.Domain.Entities.Book", "Book")
                        .WithMany("Chapters")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("CreativeLongform.Domain.Entities.ComplianceEvaluation", b =>
                {
                    b.HasOne("CreativeLongform.Domain.Entities.GenerationRun", "GenerationRun")
                        .WithMany("ComplianceEvaluations")
                        .HasForeignKey("GenerationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GenerationRun");
                });

            modelBuilder.Entity("CreativeLongform.Domain.Entities.GenerationRun", b =>
                {
                    b.HasOne("CreativeLongform.Domain.Entities.Scene", "Scene")
                        .WithMany("GenerationRuns")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("CreativeLongform.Domain.Entities.LlmCall", b =>
                {
                    b.HasOne("CreativeLongform.Domain.Entities.Book", "Book")
                        .WithMany("WorldLlmCalls")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CreativeLongform.Domain.Entities.GenerationRun", "GenerationRun")
                        .WithMany("LlmCalls")
                        .HasForeignKey("GenerationRunId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Book");

                    b.Navigation("GenerationRun");
                });

            modelBuilder.Entity("CreativeLongform.Domain.Entities.Scene", b =>
                {
                    b.HasOne("CreativeLongform.Domain.Entities.Chapter", "Chapter")
                        .WithMany("Scenes")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("CreativeLongform.Domain.Entities.SceneWorldElement", b =>
                {
                    b.HasOne("CreativeLongform.Domain.Entities.Scene", "Scene")
                        .WithMany("SceneWorldElements")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CreativeLongform.Domain.Entities.WorldElement", "WorldElement")
                        .WithMany("SceneWorldElements")
                        .HasForeignKey("WorldElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scene");

                    b.Navigation("WorldElement");
                });

            modelBuilder.Entity("CreativeLongform.Domain.Entities.StateSnapshot", b =>
                {
                    b.HasOne("CreativeLongform.Domain.Entities.GenerationRun", "GenerationRun")
                        .WithMany("StateSnapshots")
                        .HasForeignKey("GenerationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GenerationRun");
                });

            modelBuilder.Entity("CreativeLongform.Domain.Entities.TimelineEntry", b =>
                {
                    b.HasOne("CreativeLongform.Domain.Entities.Book", "Book")
                        .WithMany("TimelineEntries")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CreativeLongform.Domain.Entities.Scene", "Scene")
                        .WithOne("TimelineEntry")
                        .HasForeignKey("CreativeLongform.Domain.Entities.TimelineEntry", "SceneId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CreativeLongform.Domain.Entities.WorldElement", "WorldElement")
                        .WithMany("TimelineEntries")
                        .HasForeignKey("WorldElementId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Book");

                    b.Navigation("Scene");

                    b.Navigation("WorldElement");
                });

            modelBuilder.Entity("CreativeLongform.Domain.Entities.WorldElement", b =>
                {
                    b.HasOne("CreativeLongform.Domain.Entities.Book", "Book")
                        .WithMany("WorldElements")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("CreativeLongform.Domain.Entities.WorldElementLink", b =>
                {
                    b.HasOne("CreativeLongform.Domain.Entities.WorldElement", "FromWorldElement")
                        .WithMany("OutgoingLinks")
                        .HasForeignKey("FromWorldElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CreativeLongform.Domain.Entities.WorldElement", "ToWorldElement")
                        .WithMany("IncomingLinks")
                        .HasForeignKey("ToWorldElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromWorldElement");

                    b.Navigation("ToWorldElement");
                });

            modelBuilder.Entity("CreativeLongform.Domain.Entities.Book", b =>
                {
                    b.Navigation("Chapters");

                    b.Navigation("TimelineEntries");

                    b.Navigation("WorldElements");

                    b.Navigation("WorldLlmCalls");
                });

            modelBuilder.Entity("CreativeLongform.Domain.Entities.Chapter", b =>
                {
                    b.Navigation("Scenes");
                });

            modelBuilder.Entity("CreativeLongform.Domain.Entities.GenerationRun", b =>
                {
                    b.Navigation("ComplianceEvaluations");

                    b.Navigation("LlmCalls");

                    b.Navigation("StateSnapshots");
                });

            modelBuilder.Entity("CreativeLongform.Domain.Entities.Scene", b =>
                {
                    b.Navigation("GenerationRuns");

                    b.Navigation("SceneWorldElements");

                    b.Navigation("TimelineEntry");
                });

            modelBuilder.Entity("CreativeLongform.Domain.Entities.WorldElement", b =>
                {
                    b.Navigation("IncomingLinks");

                    b.Navigation("OutgoingLinks");

                    b.Navigation("SceneWorldElements");

                    b.Navigation("TimelineEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
