#!/usr/bin/env bash
# Interactive stack setup: Ollama CPU vs GPU, model choice, deploy via Docker Compose.
# Run from repo root: make setup   (or: bash scripts/setup.sh)

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

ENV_FILE="$ROOT/.env"
OVERRIDE_FILE="$ROOT/docker-compose.override.yml"

die() {
  echo "Error: $*" >&2
  exit 1
}

have_cmd() {
  command -v "$1" >/dev/null 2>&1
}

# Host NVIDIA visible to this shell (driver + nvidia-smi).
detect_nvidia_host() {
  have_cmd nvidia-smi || return 1
  nvidia-smi -L >/dev/null 2>&1
}

# Docker reports the nvidia runtime (Container Toolkit / Docker Desktop with GPU).
detect_docker_gpu() {
  docker info 2>/dev/null | grep -qi 'nvidia' && return 0
  return 1
}

# First GPU total VRAM in MiB (nvidia-smi), or 0 if unknown.
query_gpu_vram_mib() {
  local line
  line=$(nvidia-smi --query-gpu=memory.total --format=csv,noheader 2>/dev/null | head -1 || true)
  [[ -z "$line" ]] && echo 0 && return
  echo "$line" | grep -oE '[0-9]+' | head -1
}

# Minimum VRAM (MiB) to offer each curated model (weights + headroom vs Ollama size labels).
VRAM_MIN_QWEN2_5_14B_Q4_K_M=11000
VRAM_MIN_MISTRAL_NEMO_12B_Q4_K_M=12000
VRAM_MIN_GEMMA3_27B_Q3_K_M=22000

write_env() {
  local model="$1"
  umask 077
  cat >"$ENV_FILE" <<EOF
# Generated by scripts/setup.sh — local only (.gitignore covers .env)
OLLAMA_MODEL=${model}
EOF
  echo "Wrote $ENV_FILE"
}

write_gpu_override() {
  cat >"$OVERRIDE_FILE" <<'EOF'
# Generated by scripts/setup.sh — local only (gitignored)
services:
  ollama:
    gpus: all
EOF
  echo "Wrote $OVERRIDE_FILE (Ollama will use NVIDIA GPU in Docker)"
}

remove_gpu_override() {
  if [[ -f "$OVERRIDE_FILE" ]]; then
    rm -f "$OVERRIDE_FILE"
    echo "Removed $OVERRIDE_FILE (CPU-only Ollama)"
  fi
}

# Ollama tags for curated options (see https://ollama.com/library).
TAG_QWEN2_5_14B_Q4_K_M="qwen2.5:14b-instruct-q4_K_M"
TAG_MISTRAL_NEMO_12B_Q4_K_M="mistral-nemo:12b-instruct-2407-q4_K_M"
TAG_GEMMA3_27B_Q3_K_M="gemma3:27b-instruct-q3_K_M"

prompt_model_cpu() {
  local choice
  echo "" >&2
  echo "Choose a model for Writer and Critic (same model for both):" >&2
  echo "  1) llama3.2   (default)" >&2
  echo "  2) mistral" >&2
  echo "  3) llama3.1" >&2
  echo "  4) phi3" >&2
  echo "  5) Enter another tag (e.g. codellama, qwen2.5)" >&2
  read -r -p "Choice [1-5, default 1]: " choice
  choice="${choice:-1}"
  case "$choice" in
    1|"") echo "llama3.2" ;;
    2) echo "mistral" ;;
    3) echo "llama3.1" ;;
    4) echo "phi3" ;;
    5)
      read -r -p "Model name: " custom
      [[ -n "${custom// }" ]] || die "Model name cannot be empty"
      echo "$custom"
      ;;
    *) die "Invalid choice: $choice" ;;
  esac
}

prompt_model_gpu() {
  local vram_mib="${1:-0}"
  local labels=()
  local tags=()
  local choice
  local n idx num_opts

  if [[ "$vram_mib" -eq 0 ]]; then
    echo "" >&2
    echo "Could not read GPU VRAM from nvidia-smi; listing curated models anyway—confirm your card can hold the weights." >&2
    vram_mib=2147483647
  fi

  if [[ "$vram_mib" -ge $VRAM_MIN_QWEN2_5_14B_Q4_K_M ]]; then
    labels+=("Qwen2.5 14B instruct (Q4_K_M) — $TAG_QWEN2_5_14B_Q4_K_M")
    tags+=("$TAG_QWEN2_5_14B_Q4_K_M")
  fi
  if [[ "$vram_mib" -ge $VRAM_MIN_MISTRAL_NEMO_12B_Q4_K_M ]]; then
    labels+=("Mistral Nemo 12B instruct (Q4_K_M) — $TAG_MISTRAL_NEMO_12B_Q4_K_M")
    tags+=("$TAG_MISTRAL_NEMO_12B_Q4_K_M")
  fi
  if [[ "$vram_mib" -ge $VRAM_MIN_GEMMA3_27B_Q3_K_M ]]; then
    labels+=("Gemma3 27B instruct (Q3_K_M) — $TAG_GEMMA3_27B_Q3_K_M")
    tags+=("$TAG_GEMMA3_27B_Q3_K_M")
  fi

  labels+=("llama3.2" "mistral" "llama3.1" "phi3" "Enter another tag")
  tags+=("llama3.2" "mistral" "llama3.1" "phi3" "__custom__")

  echo "" >&2
  echo "GPU mode: curated LLMs appear only when the first GPU's total VRAM meets the listed minimum." >&2
  echo "Choose a model for Writer and Critic (same model for both):" >&2
  n=1
  for idx in "${!labels[@]}"; do
    echo "  $n) ${labels[$idx]}" >&2
    ((n++)) || true
  done
  num_opts=$((${#labels[@]}))
  read -r -p "Choice [1-$num_opts, default 1]: " choice
  choice="${choice:-1}"
  [[ "$choice" =~ ^[0-9]+$ ]] || die "Invalid choice: $choice"
  ((choice >= 1 && choice <= num_opts)) || die "Invalid choice: $choice"
  local pick="${tags[$((choice - 1))]}"
  if [[ "$pick" == "__custom__" ]]; then
    read -r -p "Model name (Ollama tag): " custom
    [[ -n "${custom// }" ]] || die "Model name cannot be empty"
    echo "$custom"
    return
  fi
  echo "$pick"
}

prompt_model() {
  local use_gpu="$1"
  local vram_mib="${2:-0}"
  if [[ "$use_gpu" == true ]]; then
    prompt_model_gpu "$vram_mib"
  else
    prompt_model_cpu
  fi
}

echo "=== Creative Longform — setup ==="
echo ""

use_gpu=false
if detect_nvidia_host; then
  echo "NVIDIA GPU detected (nvidia-smi)."
  if detect_docker_gpu; then
    read -r -p "Use NVIDIA GPU for the Ollama container? [y/N]: " gpu_ans
    case "${gpu_ans:-}" in
      y|Y|yes|YES) use_gpu=true ;;
      *) use_gpu=false ;;
    esac
  else
    echo "Docker does not report GPU support (install NVIDIA Container Toolkit or enable GPU in Docker Desktop)."
    read -r -p "Still try GPU for Ollama (may fail at runtime)? [y/N]: " gpu_force
    case "${gpu_force:-}" in
      y|Y|yes|YES) use_gpu=true ;;
      *) use_gpu=false ;;
    esac
  fi
else
  echo "No NVIDIA GPU detected from this shell (nvidia-smi missing or no devices)."
  echo "Using CPU for Ollama in Docker."
  use_gpu=false
fi

if [[ "$use_gpu" == true ]]; then
  write_gpu_override
else
  remove_gpu_override
fi

vram_mib=0
if [[ "$use_gpu" == true ]]; then
  vram_mib=$(query_gpu_vram_mib)
  if [[ "$vram_mib" =~ ^[0-9]+$ ]]; then
    echo "Detected GPU VRAM (first device): ${vram_mib} MiB"
  else
    vram_mib=0
  fi
fi

MODEL="$(prompt_model "$use_gpu" "$vram_mib")"
write_env "$MODEL"

echo ""
echo "Building images and starting stack (Postgres, Ollama, API, web)..."
docker compose up -d --build

echo ""
echo "Waiting for Ollama to accept connections..."
for i in $(seq 1 30); do
  if docker compose exec -T ollama ollama list >/dev/null 2>&1; then
    break
  fi
  sleep 1
done

echo "Pulling model '$MODEL' into the Ollama container (first run may take a while)..."
docker compose exec -T ollama ollama pull "$MODEL"

echo ""
echo "=== Setup complete ==="
echo "App:     http://localhost:8080"
echo "Swagger: http://localhost:8080/swagger"
echo "API uses Ollama model: $MODEL (see $ENV_FILE)"
if [[ "$use_gpu" == true ]]; then
  echo "Ollama GPU: enabled ($OVERRIDE_FILE)"
else
  echo "Ollama GPU: off (CPU)"
fi
