#!/usr/bin/env bash
# Interactive stack setup: Ollama CPU vs GPU, model choice, deploy via Docker Compose.
# Run from repo root: make setup   (or: bash scripts/setup.sh)

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

ENV_FILE="$ROOT/.env"
OVERRIDE_FILE="$ROOT/docker-compose.override.yml"

die() {
  echo "Error: $*" >&2
  exit 1
}

have_cmd() {
  command -v "$1" >/dev/null 2>&1
}

# Host NVIDIA visible to this shell (driver + nvidia-smi).
detect_nvidia_host() {
  have_cmd nvidia-smi || return 1
  nvidia-smi -L >/dev/null 2>&1
}

# Docker reports the nvidia runtime (Container Toolkit / Docker Desktop with GPU).
detect_docker_gpu() {
  docker info 2>/dev/null | grep -qi 'nvidia' && return 0
  return 1
}

# First GPU total VRAM in MiB (nvidia-smi), or 0 if unknown.
query_gpu_vram_mib() {
  local line
  line=$(nvidia-smi --query-gpu=memory.total --format=csv,noheader 2>/dev/null | head -1 || true)
  [[ -z "$line" ]] && echo 0 && return
  echo "$line" | grep -oE '[0-9]+' | head -1
}

# Minimum VRAM (MiB) to offer each curated model (weights + headroom vs Ollama size labels).
VRAM_MIN_QWEN2_5_14B_Q4_K_M=11000
VRAM_MIN_MISTRAL_NEMO_12B_Q4_K_M=12000
VRAM_MIN_GEMMA3_27B_Q3_K_M=22000

write_env() {
  local model="$1"
  umask 077
  cat >"$ENV_FILE" <<EOF
# Generated by scripts/setup.sh — local only (.gitignore covers .env)
#
# docker-compose.yml maps this to the API container as Ollama__WriterModel and Ollama__CriticModel.
# If you edit OLLAMA_MODEL by hand, recreate the API so it picks up the new value, e.g.:
#   docker compose up -d --force-recreate api
# (or: make deploy)
#
# The .NET host does NOT load this file. If you run the API with "dotnet run" instead of Docker,
# set environment variables Ollama__WriterModel / Ollama__CriticModel or edit appsettings.json.
OLLAMA_MODEL=${model}
EOF
  echo "Wrote $ENV_FILE"
}

# Ensure import directory exists (for docker cp / compose cp fallbacks).
ensure_ollama_import_dir() {
  docker compose exec -T ollama sh -c "mkdir -p '/root/.ollama/custom-imports/${IMPORT_NAME}'"
}

# Stream a host GGUF into the container. mkdir and cat MUST run in the same exec — a separate mkdir often leaves
# the path missing before cat (race / different session), causing "Directory nonexistent".
gguf_copy_via_stdin() {
  local host_file="$1"
  docker compose exec -T ollama sh -c "mkdir -p '/root/.ollama/custom-imports/${IMPORT_NAME}' && cat > '/root/.ollama/custom-imports/${IMPORT_NAME}/model.gguf'" < "$host_file"
}

# Copy host file into Ollama.
# Docker Desktop + Git Bash: both `docker compose cp` and `docker cp` use a tar path that often fails on multi-GB
# files ("read/write on closed pipe"). Prefer stdin streaming on MSYS; fall back to cp methods, then stdin again.
docker_compose_cp_gguf_into_ollama() {
  local host_file="$1"
  local dest_in_container="/root/.ollama/custom-imports/${IMPORT_NAME}/model.gguf"
  local host_for_docker="$host_file"

  ensure_ollama_import_dir

  if [[ -n "${MSYSTEM:-}" ]] || [[ "${OSTYPE:-}" == msys* ]]; then
    echo "Copying GGUF via stdin (avoids Docker cp tar bugs for large files on Windows)..." >&2
    if gguf_copy_via_stdin "$host_file"; then
      return 0
    fi
    echo "stdin copy failed; trying docker compose cp / docker cp..." >&2
  fi

  if [[ -z "${WSL_DISTRO_NAME:-}" ]] && command -v cygpath >/dev/null 2>&1; then
    if [[ -n "${MSYSTEM:-}" ]] || [[ "${OSTYPE:-}" == msys* ]]; then
      host_for_docker="$(cygpath -w "$host_file")"
    fi
  fi

  if MSYS_NO_PATHCONV=1 docker compose cp "$host_for_docker" "ollama:${dest_in_container}"; then
    return 0
  fi

  echo "docker compose cp failed; retrying with docker cp..." >&2
  local cid
  cid="$(docker compose ps -q ollama 2>/dev/null || true)"
  [[ -n "$cid" ]] || die "Could not resolve Ollama container id. Is the stack running?"
  if MSYS_NO_PATHCONV=1 docker cp "$host_for_docker" "${cid}:${dest_in_container}"; then
    return 0
  fi

  echo "Retrying copy via stdin..." >&2
  gguf_copy_via_stdin "$host_file" && return 0

  die "Failed to copy GGUF into the Ollama container. Try: run setup from WSL with a /mnt/c/... path, or copy the GGUF into the project folder and use a short relative path."
}

# Copy a GGUF from the host filesystem into the Ollama container and run `ollama create` (Modelfile: FROM ./model.gguf).
# Requires IMPORT_NAME set. Argument: absolute or relative path to the .gguf on this machine.
ollama_import_gguf_copy_into_ollama_and_create() {
  local host_gguf="$1"
  [[ -n "$host_gguf" ]] || die "GGUF path is empty"
  [[ -f "$host_gguf" ]] || die "GGUF file not found (not a regular file): $host_gguf"
  [[ -r "$host_gguf" ]] || die "GGUF file is not readable: $host_gguf"

  echo "Registering as Ollama model '$IMPORT_NAME'..." >&2
  docker_compose_cp_gguf_into_ollama "$host_gguf"
  docker compose exec -T ollama sh -c "cd /root/.ollama/custom-imports/${IMPORT_NAME} && printf 'FROM ./model.gguf\n' > Modelfile && ollama create \"${IMPORT_NAME}\" -f Modelfile"
}

# Requires IMPORT_URL and IMPORT_NAME (from prompt_custom_gguf_from_url).
ollama_import_gguf_from_url() {
  local tmpdir
  tmpdir="$(mktemp -d)"
  trap 'rm -rf "$tmpdir"' RETURN

  echo "Downloading GGUF from URL (host) — then copying into Ollama..." >&2
  if command -v curl >/dev/null 2>&1; then
    curl -fL --progress-bar -o "$tmpdir/model.gguf" "$IMPORT_URL"
  elif command -v wget >/dev/null 2>&1; then
    wget -O "$tmpdir/model.gguf" "$IMPORT_URL"
  else
    die "Install curl or wget on this machine to download a GGUF from a URL."
  fi

  ollama_import_gguf_copy_into_ollama_and_create "$tmpdir/model.gguf"
}

# Requires LOCAL_GGUF_PATH and IMPORT_NAME (from prompt_custom_gguf_local_path).
ollama_import_gguf_from_local_file() {
  ollama_import_gguf_copy_into_ollama_and_create "$LOCAL_GGUF_PATH"
}

write_gpu_override() {
  cat >"$OVERRIDE_FILE" <<'EOF'
# Generated by scripts/setup.sh — local only (gitignored)
services:
  ollama:
    gpus: all
EOF
  echo "Wrote $OVERRIDE_FILE (Ollama will use NVIDIA GPU in Docker)"
}

remove_gpu_override() {
  if [[ -f "$OVERRIDE_FILE" ]]; then
    rm -f "$OVERRIDE_FILE"
    echo "Removed $OVERRIDE_FILE (CPU-only Ollama)"
  fi
}

# Ollama tags for curated options (see https://ollama.com/library).
TAG_QWEN2_5_14B_Q4_K_M="qwen2.5:14b-instruct-q4_K_M"
TAG_MISTRAL_NEMO_12B_Q4_K_M="mistral-nemo:12b-instruct-2407-q4_K_M"
TAG_GEMMA3_27B_Q3_K_M="gemma3:27b-instruct-q3_K_M"

prompt_model_cpu() {
  local choice
  echo "" >&2
  echo "Choose a model for Writer and Critic (same model for both):" >&2
  echo "  1) llama3.2   (default)" >&2
  echo "  2) mistral" >&2
  echo "  3) llama3.1" >&2
  echo "  4) phi3" >&2
  echo "  5) Enter another tag (e.g. codellama, qwen2.5)" >&2
  read -r -p "Choice [1-5, default 1]: " choice
  choice="${choice:-1}"
  case "$choice" in
    1|"") echo "llama3.2" ;;
    2) echo "mistral" ;;
    3) echo "llama3.1" ;;
    4) echo "phi3" ;;
    5)
      read -r -p "Model name: " custom
      [[ -n "${custom// }" ]] || die "Model name cannot be empty"
      echo "$custom"
      ;;
    *) die "Invalid choice: $choice" ;;
  esac
}

prompt_model_gpu() {
  local vram_mib="${1:-0}"
  local labels=()
  local tags=()
  local choice
  local n idx num_opts

  if [[ "$vram_mib" -eq 0 ]]; then
    echo "" >&2
    echo "Could not read GPU VRAM from nvidia-smi; listing curated models anyway—confirm your card can hold the weights." >&2
    vram_mib=2147483647
  fi

  if [[ "$vram_mib" -ge $VRAM_MIN_QWEN2_5_14B_Q4_K_M ]]; then
    labels+=("Qwen2.5 14B instruct (Q4_K_M) — $TAG_QWEN2_5_14B_Q4_K_M")
    tags+=("$TAG_QWEN2_5_14B_Q4_K_M")
  fi
  if [[ "$vram_mib" -ge $VRAM_MIN_MISTRAL_NEMO_12B_Q4_K_M ]]; then
    labels+=("Mistral Nemo 12B instruct (Q4_K_M) — $TAG_MISTRAL_NEMO_12B_Q4_K_M")
    tags+=("$TAG_MISTRAL_NEMO_12B_Q4_K_M")
  fi
  if [[ "$vram_mib" -ge $VRAM_MIN_GEMMA3_27B_Q3_K_M ]]; then
    labels+=("Gemma3 27B instruct (Q3_K_M) — $TAG_GEMMA3_27B_Q3_K_M")
    tags+=("$TAG_GEMMA3_27B_Q3_K_M")
  fi

  labels+=("llama3.2" "mistral" "llama3.1" "phi3" "Enter another tag")
  tags+=("llama3.2" "mistral" "llama3.1" "phi3" "__custom__")

  echo "" >&2
  echo "GPU mode: curated LLMs appear only when the first GPU's total VRAM meets the listed minimum." >&2
  echo "Choose a model for Writer and Critic (same model for both):" >&2
  n=1
  for idx in "${!labels[@]}"; do
    echo "  $n) ${labels[$idx]}" >&2
    ((n++)) || true
  done
  num_opts=$((${#labels[@]}))
  read -r -p "Choice [1-$num_opts, default 1]: " choice
  choice="${choice:-1}"
  [[ "$choice" =~ ^[0-9]+$ ]] || die "Invalid choice: $choice"
  ((choice >= 1 && choice <= num_opts)) || die "Invalid choice: $choice"
  local pick="${tags[$((choice - 1))]}"
  if [[ "$pick" == "__custom__" ]]; then
    read -r -p "Model name (Ollama tag): " custom
    [[ -n "${custom// }" ]] || die "Model name cannot be empty"
    echo "$custom"
    return
  fi
  echo "$pick"
}

prompt_model() {
  local use_gpu="$1"
  local vram_mib="${2:-0}"
  if [[ "$use_gpu" == true ]]; then
    prompt_model_gpu "$vram_mib"
  else
    prompt_model_cpu
  fi
}

prompt_common_ollama_import_name() {
  echo "" >&2
  read -r -p "Ollama model name for this file (e.g. my-writer; letters, numbers, . _ - :) " CUSTOM_IMPORT_NAME
  CUSTOM_IMPORT_NAME="${CUSTOM_IMPORT_NAME//[[:space:]]/}"
  [[ -n "$CUSTOM_IMPORT_NAME" ]] || die "Model name cannot be empty"
  case "$CUSTOM_IMPORT_NAME" in
    *[!a-zA-Z0-9._:-]*)
      die "Model name may only contain letters, numbers, and . _ - :"
      ;;
  esac
  IMPORT_NAME="$CUSTOM_IMPORT_NAME"
}

# Sets IMPORT_URL, IMPORT_NAME; caller sets MODEL=CUSTOM_IMPORT_NAME after.
prompt_custom_gguf_from_url() {
  echo "" >&2
  echo "Custom GGUF from URL — use a direct link to a .gguf file (HTTPS recommended)." >&2
  echo "Example: a GitHub release asset or Hugging Face file URL ending in .gguf" >&2
  read -r -p "URL: " IMPORT_URL
  IMPORT_URL="${IMPORT_URL//[[:space:]]/}"
  [[ -n "$IMPORT_URL" ]] || die "URL cannot be empty"
  case "$IMPORT_URL" in
    http://*|https://*) ;;
    *) die "URL must start with http:// or https://" ;;
  esac
  prompt_common_ollama_import_name
}

# Sets LOCAL_GGUF_PATH, IMPORT_NAME; caller sets MODEL=CUSTOM_IMPORT_NAME after.
prompt_custom_gguf_local_path() {
  echo "" >&2
  echo "Local GGUF file — absolute path or path relative to the repo root ($ROOT)." >&2
  echo "Tip: on Windows (Git Bash) you can use /c/Users/... or D:/path/to/model.gguf" >&2
  read -r -p "Path to .gguf file: " LOCAL_GGUF_PATH
  LOCAL_GGUF_PATH="${LOCAL_GGUF_PATH#"${LOCAL_GGUF_PATH%%[![:space:]]*}"}"
  LOCAL_GGUF_PATH="${LOCAL_GGUF_PATH%"${LOCAL_GGUF_PATH##*[![:space:]]}"}"
  [[ -n "$LOCAL_GGUF_PATH" ]] || die "Path cannot be empty"
  case "$LOCAL_GGUF_PATH" in
    ~/*) LOCAL_GGUF_PATH="$HOME/${LOCAL_GGUF_PATH#~/}" ;;
    "~") LOCAL_GGUF_PATH="$HOME" ;;
  esac
  # Relative paths are resolved from repo root; absolute Unix paths and Windows drive paths (C:/ or C:\) stay as-is.
  if [[ "$LOCAL_GGUF_PATH" != /* ]] && [[ ! "$LOCAL_GGUF_PATH" =~ ^[A-Za-z]:[\\/] ]]; then
    LOCAL_GGUF_PATH="$ROOT/$LOCAL_GGUF_PATH"
  fi
  [[ -f "$LOCAL_GGUF_PATH" ]] || die "File not found: $LOCAL_GGUF_PATH"
  [[ -r "$LOCAL_GGUF_PATH" ]] || die "File is not readable: $LOCAL_GGUF_PATH"
  case "${LOCAL_GGUF_PATH,,}" in
    *.gguf) ;;
    *) echo "Warning: path does not end in .gguf — continuing anyway." >&2 ;;
  esac
  prompt_common_ollama_import_name
}

prompt_how_to_install_model() {
  local choice
  echo "" >&2
  echo "How do you want to install the language model?" >&2
  echo "  1) Pull from the Ollama library (ollama pull — recommended)" >&2
  echo "  2) Download a GGUF file from a URL and register it (ollama create — advanced)" >&2
  echo "  3) Use a GGUF file already on this machine (copy into Ollama — advanced)" >&2
  read -r -p "Choice [1-3, default 1]: " choice
  choice="${choice:-1}"
  case "$choice" in
    1|"") echo "library" ;;
    2) echo "url" ;;
    3) echo "local" ;;
    *) die "Invalid choice: $choice" ;;
  esac
}

echo "=== Creative Longform — setup ==="
echo ""

use_gpu=false
if detect_nvidia_host; then
  echo "NVIDIA GPU detected (nvidia-smi)."
  if detect_docker_gpu; then
    read -r -p "Use NVIDIA GPU for the Ollama container? [Y/n]: " gpu_ans
    gpu_ans="${gpu_ans:-Y}"
    case "$gpu_ans" in
      n|N|no|NO) use_gpu=false ;;
      *) use_gpu=true ;;
    esac
  else
    echo "Docker does not report GPU support (install NVIDIA Container Toolkit or enable GPU in Docker Desktop)."
    read -r -p "Still try GPU for Ollama (may fail at runtime)? [Y/n]: " gpu_force
    gpu_force="${gpu_force:-Y}"
    case "$gpu_force" in
      n|N|no|NO) use_gpu=false ;;
      *) use_gpu=true ;;
    esac
  fi
else
  echo "No NVIDIA GPU detected from this shell (nvidia-smi missing or no devices)."
  echo "Using CPU for Ollama in Docker."
  use_gpu=false
fi

if [[ "$use_gpu" == true ]]; then
  write_gpu_override
else
  remove_gpu_override
fi

vram_mib=0
if [[ "$use_gpu" == true ]]; then
  vram_mib=$(query_gpu_vram_mib)
  if [[ "$vram_mib" =~ ^[0-9]+$ ]]; then
    echo "Detected GPU VRAM (first device): ${vram_mib} MiB"
  else
    vram_mib=0
  fi
fi

INSTALL_KIND="$(prompt_how_to_install_model)"
IMPORT_URL=""
LOCAL_GGUF_PATH=""
CUSTOM_IMPORT_NAME=""
IMPORT_NAME=""

if [[ "$INSTALL_KIND" == "url" ]]; then
  prompt_custom_gguf_from_url
  MODEL="$CUSTOM_IMPORT_NAME"
elif [[ "$INSTALL_KIND" == "local" ]]; then
  prompt_custom_gguf_local_path
  MODEL="$CUSTOM_IMPORT_NAME"
else
  MODEL="$(prompt_model "$use_gpu" "$vram_mib")"
fi

write_env "$MODEL"

echo ""
echo "Building images and starting stack (Postgres, Ollama, API, web)..."
docker compose up -d --build

echo ""
echo "Waiting for Ollama to accept connections..."
for i in $(seq 1 30); do
  if docker compose exec -T ollama ollama list >/dev/null 2>&1; then
    break
  fi
  sleep 1
done

if [[ "$INSTALL_KIND" == "url" ]]; then
  echo "Importing custom GGUF from URL into the Ollama container..."
  ollama_import_gguf_from_url
elif [[ "$INSTALL_KIND" == "local" ]]; then
  echo "Importing local GGUF into the Ollama container..."
  ollama_import_gguf_from_local_file
else
  echo "Pulling model '$MODEL' into the Ollama container (first run may take a while)..."
  docker compose exec -T ollama ollama pull "$MODEL"
fi

echo ""
echo "=== Setup complete ==="
echo "App:     http://localhost:8080"
echo "Swagger: http://localhost:8080/swagger"
echo "API uses Ollama model: $MODEL (see $ENV_FILE)"
if [[ "$use_gpu" == true ]]; then
  echo "Ollama GPU: enabled ($OVERRIDE_FILE)"
else
  echo "Ollama GPU: off (CPU)"
fi
